============================================================================================== 
Warning! Mixing Conda and module environments may lead to corruption of the
user environment. 
We do not recommend users mixing those two environments unless absolutely
necessary. Note that 
SURF does not provide any support for Conda environment.
For more information, please refer to our software policy page:
https://servicedesk.surf.nl/wiki/display/WIKI/Software+policy+Snellius+and+Lisa#SoftwarepolicySnelliusandLisa-UseofAnacondaandMinicondaenvironmentsonSnellius 

Remember that many packages have already been installed on the system and can
be loaded using 
the 'module load <package__name>' command. If you are uncertain if a package is
already available 
on the system, please use 'module avail' or 'module spider' to search for it.
============================================================================================== 
mkdir: cannot create directory '/scur1301': Permission denied
Traceback (most recent call last):
  File "/gpfs/home6/scur1301/uvadlc_practicals_2023/assignment2/part2/.//clipzs.py", line 396, in <module>
    main()
  File "/gpfs/home6/scur1301/uvadlc_practicals_2023/assignment2/part2/.//clipzs.py", line 331, in main
    dataset = load_dataset(args.dataset, args.root, args.split, preprocess)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/home6/scur1301/uvadlc_practicals_2023/assignment2/part2/.//clipzs.py", line 263, in load_dataset
    dataset = DATASET[dataset](
              ^^^^^^^^^^^^^^^^^
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/cifar.py", line 65, in __init__
    self.download()
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/cifar.py", line 139, in download
    download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/utils.py", line 434, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/utils.py", line 123, in download_url
    os.makedirs(root, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/scur1301'
Traceback (most recent call last):
  File "/gpfs/home6/scur1301/uvadlc_practicals_2023/assignment2/part2/.//clipzs.py", line 396, in <module>
    main()
  File "/gpfs/home6/scur1301/uvadlc_practicals_2023/assignment2/part2/.//clipzs.py", line 331, in main
    dataset = load_dataset(args.dataset, args.root, args.split, preprocess)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/home6/scur1301/uvadlc_practicals_2023/assignment2/part2/.//clipzs.py", line 263, in load_dataset
    dataset = DATASET[dataset](
              ^^^^^^^^^^^^^^^^^
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/cifar.py", line 65, in __init__
    self.download()
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/cifar.py", line 139, in download
    download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/utils.py", line 434, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/utils.py", line 123, in download_url
    os.makedirs(root, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/scur1301'
Traceback (most recent call last):
  File "/gpfs/home6/scur1301/uvadlc_practicals_2023/assignment2/part2/.//clipzs.py", line 396, in <module>
    main()
  File "/gpfs/home6/scur1301/uvadlc_practicals_2023/assignment2/part2/.//clipzs.py", line 331, in main
    dataset = load_dataset(args.dataset, args.root, args.split, preprocess)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/home6/scur1301/uvadlc_practicals_2023/assignment2/part2/.//clipzs.py", line 263, in load_dataset
    dataset = DATASET[dataset](
              ^^^^^^^^^^^^^^^^^
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/cifar.py", line 65, in __init__
    self.download()
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/cifar.py", line 139, in download
    download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/utils.py", line 434, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/utils.py", line 123, in download_url
    os.makedirs(root, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/scur1301'
Traceback (most recent call last):
  File "/gpfs/home6/scur1301/uvadlc_practicals_2023/assignment2/part2/.//clipzs.py", line 396, in <module>
    main()
  File "/gpfs/home6/scur1301/uvadlc_practicals_2023/assignment2/part2/.//clipzs.py", line 331, in main
    dataset = load_dataset(args.dataset, args.root, args.split, preprocess)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/home6/scur1301/uvadlc_practicals_2023/assignment2/part2/.//clipzs.py", line 263, in load_dataset
    dataset = DATASET[dataset](
              ^^^^^^^^^^^^^^^^^
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/cifar.py", line 65, in __init__
    self.download()
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/cifar.py", line 139, in download
    download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/utils.py", line 434, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/scur1301/.conda/envs/dl2023/lib/python3.11/site-packages/torchvision/datasets/utils.py", line 123, in download_url
    os.makedirs(root, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/scur1301'

JOB STATISTICS
==============
Job ID: 4515060
Cluster: snellius
User/Group: scur1301/scur1301
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 00:00:00
CPU Efficiency: 0.00% of 00:11:06 core-walltime
Job Wall-clock time: 00:00:37
Memory Utilized: 0.00 MB (estimated maximum)
Memory Efficiency: 0.00% of 31.25 GB (31.25 GB/node)
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
